#!/usr/bin/env python3

import logging
from GyroBalancer import GyroBalancer


class BALANC3R(GyroBalancer):
    """
    Laurens Valk's BALANC3R
    http://robotsquare.com/2014/06/23/tutorial-building-balanc3r/
    """
    def __init__(self):
        GyroBalancer.__init__(self, # 1にした, デジタルにした, , ...
                              gainGyroAngle=39.7164, #31.9978, #900, # K_F[1]
                              gainGyroRate=4.0376, #2.78873, #110, # K_F[3]
                              gainMotorAngle=0.8432, #0.870303, #9, # K_F[0]
                              gainMotorAngularSpeed=1.124 * 0.85, #6, # K_F[2]
                              gainMotorAngleErrorAccumulated=0.44721) #3) # K_I


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG,
                        format='%(asctime)s %(levelname)5s: %(message)s')
    log = logging.getLogger(__name__)

    log.info("Starting BALANC3R")
    robot = BALANC3R()
    robot.main()
    # robot.set_moter_barance()
    log.info("Exiting BALANC3R")
