#!/usr/bin/env python3

import logging
from GyroBalancer import GyroBalancer


class BALANC3R(GyroBalancer):
    """
    Laurens Valk's BALANC3R
    http://robotsquare.com/2014/06/23/tutorial-building-balanc3r/
    """
    def __init__(self):
        GyroBalancer.__init__(self,
                              gainGyroAngle=31.9978, #900,
                              gainGyroRate=2.78873, #110,
                              gainMotorAngle=0.870303, #9,
                              gainMotorAngularSpeed=1.1566 * 0.6, #6,
                              gainMotorAngleErrorAccumulated=0.44721) #3)


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG,
                        format='%(asctime)s %(levelname)5s: %(message)s')
    log = logging.getLogger(__name__)

    log.info("Starting BALANC3R")
    robot = BALANC3R()
    robot.main()
    # robot.set_moter_barance()
    log.info("Exiting BALANC3R")
